### ISSUE TITLE
convert_ucf101 was failed to open avi files in UCF101 dataset

### ISSUE THREAD

**Issue by zlinker** [wps712/caffe_rnn#9]
Hello wps, good to see your repository, a nice job. but after make the caffe successfully, it threw out a problem that the video converter can't work when opening the avi files.
I checked my opencv config and there was no problem because I can open the same video filepath on my test program, of course the filepath were no mistake. would you mind solve about it ?  thank you.

**Comment by peiswang** [comment]
I have just tested on my machine and it runs ok. What's the error log? 
By the way, this method does not work well and I don't work on it any more.

**Comment by zlinker** [comment]
sorry, it does work, just some environment mistakes on my opencv before, thanks anyway :)
I think this is an interesting work, but it seems that the performance was depressing, would you mind tell me such as the accuracy for the final iteration?

**Comment by peiswang** [comment]
Sorry for not replying sooner. If I am not mistaken, the clip accuracy during testing stage is about 35%.

**Comment by zlinker** [comment]
uhhh, actually not really good, thank you :)
